### ISSUE TITLE
[FEAT] COMPONENT > Responsive User Sidebar

### ISSUE THREAD

**Issue by Mat-icon** [frank1003A/Language-learning-ai#15]
### Description
Develop the User Sidebar displayed on all the pages.

### Purpose
It provides a component for showing the navbar.

### Requirement
- Ensure that the typography (text colors, font weights, font sizes, etc.) remains consistent with the design.
- Ensure that the card design (border colors, background color, text content, etc.) remains consistent with the design.
- Ensure the logo links to the application's home route.
- Pixel perfect implementaiton

### Expected Outcome
- A component that displays the user sidebar on all pages.

### Testing
- Make use of the react testing library to write unit tests for this component (Note that this library is already installed in the project codebase).
- Test different scenarios/cases to model a real-life use of the component

### Task
- [ ] Create a navbar component and use all expected reusable components(buttons)
- [ ] Write unit tests to ensure the component works as expected.
- [ ] Proper commit message

### Links
- [Figma - Link](https://www.figma.com/design/7Jl49r5rLPVzqorAVLKF1x/Team-Language-Learning-AI?node-id=1495-9858&t=xEektLQWY8ZSAY8m-4)

### Images
![_User Side Navigation Bar](https://github.com/user-attachments/assets/9a065b79-def0-436a-9428-b8963538058d)

### Acceptance Criteria
- Create a navbar component that displays the app logo, navigation links, and every other thing according to the design
- Write unit tests for this component to model expected behavior.
