### ISSUE TITLE
[FEAT] COMPONENT > Button Component

### ISSUE THREAD

**Issue by Mat-icon** [frank1003A/Language-learning-ai#21]
### **Description:**
Create a reusable buttons

### **Acceptance Criteria:**
1. Buttons should be implemented according to the figma design.
2. Apply hover effects.

### **Expected Outcome:**
Reusable buttons with the styles properly implemented

### **Purpose:**
mute, volume increase and decrease, Feedback

### **Requirement:**
1. Design implementation as per the provided Figma designs.

### **Task:**
- [ ] Add the hover effect
- [ ] Make them reusable.
- [ ] Follow design implementation on figma

**Picture of the corresponding component/page of the ticket from the Figma:**
![_Preview Buttons](https://github.com/user-attachments/assets/f7855378-3ec8-4120-acc3-7b4b56f42562)

**Figma Link:**
- [Figma Link](https://www.figma.com/design/7Jl49r5rLPVzqorAVLKF1x/Team-Language-Learning-AI?node-id=2844-75608&t=xEektLQWY8ZSAY8m-4)
